#pragma once


namespace flounder
{
	enum biome
	{
		OCEAN, BARE, GRASSLAND, SCORCHED, SHRUBLAND, SNOW, SUBTROPICAL_DESERT, TAIGA, 
		TEMPERATE_DECIDUOUS_FOREST, TEMPERATE_DESERT, TEMPERATE_RAIN_FOREST,
		TROPICAL_RAIN_FOREST, TROPICAL_SEASONAL_FOREST, TUNDRA
	};
}