set(SPIRV_HEADERS_INCLUDES "${PROJECT_SOURCE_DIR}/Libraries/SPIRV-Headers/include")
add_subdirectory(${PROJECT_SOURCE_DIR}/Libraries/SPIRV-Headers)
set(SPIRV_HEADERS_LIBRARY "SPIRV-Headers")

set(LIBRARIES_INCLUDES ${LIBRARIES_INCLUDES} ${SPIRV_HEADERS_INCLUDES})
#set(LIBRARIES_LINKS ${LIBRARIES_LINKS} ${SPIRV_HEADERS_LIBRARY})

if(NOT SPIRV_HEADERS_LIBRARY)
	message(FATAL_ERROR "SPIRV-Headers library not found!")
endif()


set(SPIRV_TOOLS_INCLUDES "${PROJECT_SOURCE_DIR}/Libraries/SPIRV-Tools/include")
set(SPIRV_SKIP_EXECUTABLES ON CACHE INTERNAL "Skip building the executable and tests along with the library")
set(SPIRV_SKIP_TESTS ON CACHE INTERNAL "Skip building tests along with the library")
set(SKIP_SPIRV_TOOLS_INSTALL ON CACHE INTERNAL "Skip installation")
add_subdirectory(${PROJECT_SOURCE_DIR}/Libraries/SPIRV-Tools)
set(SPIRV_TOOLS_LIBRARY "SPIRV-Tools")

set(LIBRARIES_INCLUDES ${LIBRARIES_INCLUDES} ${SPIRV_TOOLS_INCLUDES})
set(LIBRARIES_LINKS ${LIBRARIES_LINKS} ${SPIRV_TOOLS_LIBRARY})

if(NOT SPIRV_TOOLS_LIBRARY)
	message(FATAL_ERROR "SPIRV-Tools library not found!")
endif()
