set(SHADERC_INCLUDES "${PROJECT_SOURCE_DIR}/Libraries/shaderc/libshaderc/include")
set(SHADERC_SKIP_INSTALL ON CACHE INTERNAL "Skip installatio")
set(SHADERC_SKIP_TESTS ON CACHE INTERNAL "Skip building tests")
set(SPIRV_SKIP_EXECUTABLES ON CACHE INTERNAL "Skip building the executable and tests along with the library")
set(SPIRV_SKIP_TESTS ON CACHE INTERNAL "Skip building tests along with the library")
set(SKIP_SPIRV_TOOLS_INSTALL ON CACHE INTERNAL "Skip installation")
set(SKIP_GLSLANG_INSTALL ON CACHE INTERNAL "Skip installation")
set(ENABLE_AMD_EXTENSIONS OFF CACHE INTERNAL "Enables support of AMD-specific extensions")
set(ENABLE_GLSLANG_BINARIES OFF CACHE INTERNAL "Builds glslangValidator and spirv-remap")
set(ENABLE_NV_EXTENSIONS OFF CACHE INTERNAL "Enables support of Nvidia-specific extensions")
set(ENABLE_HLSL ON CACHE INTERNAL "Enables HLSL input support")
set(ENABLE_OPT OFF CACHE INTERNAL "Enables spirv-opt capability if present")
add_subdirectory(${PROJECT_SOURCE_DIR}/Libraries/shaderc)
set(SHADERC_LIBRARY "HLSL" "shaderc")

set(LIBRARIES_INCLUDES ${LIBRARIES_INCLUDES} ${SHADERC_INCLUDES})
set(LIBRARIES_LINKS ${LIBRARIES_LINKS} ${SHADERC_LIBRARY})

if(NOT SHADERC_LIBRARY)
    message(FATAL_ERROR "ShaderC library not found!")
endif()
