set(BULLET_INCLUDES "${PROJECT_SOURCE_DIR}/Libraries/bullet3/src")
set(BUILD_PYBULLET OFF CACHE INTERNAL "Set when you want to build pybullet (Python bindings for Bullet)")
set(BUILD_SHARED_LIBS_SAVED "${BUILD_SHARED_LIBS}")
if(WIN32)
	set(BUILD_SHARED_LIBS OFF CACHE BOOL "Shared Libs" FORCE)
	set(USE_MSVC_RUNTIME_LIBRARY_DLL ON CACHE INTERNAL "Use MSVC Runtime Library DLL (/MD or /MDd)")
endif()
set(BUILD_BULLET3 OFF CACHE INTERNAL "Set when you want to build Bullet 3")
set(BUILD_CPU_DEMOS OFF CACHE INTERNAL "Build original Bullet CPU examples")
set(BUILD_BULLET2_DEMOS OFF CACHE INTERNAL "Set when you want to build the Bullet 2 demos")
set(USE_GRAPHICAL_BENCHMARK OFF CACHE INTERNAL "Use Graphical Benchmark")
set(BUILD_OPENGL3_DEMOS OFF CACHE INTERNAL "Set when you want to build the OpenGL3+ demos")
set(BUILD_EXTRAS OFF CACHE INTERNAL "Set when you want to build the extras")
set(USE_GLUT OFF CACHE INTERNAL "Use Glut")
set(BUILD_UNIT_TESTS OFF CACHE INTERNAL "Build Unit Tests")
add_subdirectory(${PROJECT_SOURCE_DIR}/Libraries/bullet3)
set(BUILD_SHARED_LIBS "${BUILD_SHARED_LIBS_SAVED}")
set(BULLET_LIBRARY "BulletDynamics" "BulletCollision" "LinearMath")

set(LIBRARIES_INCLUDES ${LIBRARIES_INCLUDES} ${BULLET_INCLUDES})
set(LIBRARIES_LINKS ${LIBRARIES_LINKS} ${BULLET_LIBRARY})

if(NOT BULLET_LIBRARY)
	message(FATAL_ERROR "bullet library not found!")
endif()
