set(FLOUNDEREDITOR_INC_NOFILTER
)

set(FLOUNDEREDITOR_INC_MANAGERS
)

set(FLOUNDEREDITOR_SRC_NOFILTER
	"src/Main.cpp"
)

set(FLOUNDEREDITOR_SRC_MANAGERS
)

source_group("Header Files" FILES ${FLOUNDEREDITOR_INC_NOFILTER})
source_group("Header Files//Managers" FILES ${FLOUNDEREDITOR_INC_MANAGERS})
source_group("Source Files" FILES ${FLOUNDEREDITOR_SRC_NOFILTER})
source_group("Source Files//Managers" FILES ${FLOUNDEREDITOR_SRC_MANAGERS})

set(FLOUNDEREDITOR_SRC
	${FLOUNDEREDITOR_INC_NOFILTER}
	${FLOUNDEREDITOR_SRC_NOFILTER}
	${FLOUNDEREDITOR_INC_MANAGERS}
	${FLOUNDEREDITOR_SRC_MANAGERS}
)