set(FLOUNDEREDITOR_HEADERS
)

set(FLOUNDEREDITOR_SOURCES
	"src/Main.cpp"
)

source_group("Header Files" FILES ${FLOUNDEREDITOR_HEADERS})
source_group("Source Files" FILES ${FLOUNDEREDITOR_SOURCES})

set(FLOUNDEREDITOR_SRC
	${FLOUNDEREDITOR_HEADERS}
	${FLOUNDEREDITOR_SOURCES}
)